### ISSUE TITLE
Refactor Parent/Child

### ISSUE THREAD

**Issue by Joseph-Cardwell** [shaman-ai/agent-actors#12]
It seems to me the parent/child relationship isn't really serving a purpose.

Would removing that relationship and simply dealing with them as 'workers' that can have descendants and know if they are descendant, be clearer and remove unnecessary complexity?

**Comment by CyrusOfEden** [comment]
Hey @Joseph-Cardwell! 

The parent/child semantic distinction is the same as the plan/execute semantics in Langchain's latest agent. 

Here planners can be children of another planner, like you noticed. 

Tbh I thought of worker too but it seemed to capitalistic, I thought it'd be more fun to imagine them as parents and children. 

I have something you might like... https://github.com/shaman-ai/llambdao. Check out __init__.py. The repo doesn't work yet but that's how I'm imagining future multi agent systems to be architected.

**Comment by Joseph-Cardwell** [comment]
> Hey @Joseph-Cardwell!
> 
> The parent/child semantic distinction is the same as the plan/execute semantics in Langchain's latest agent.
> 
> Here planners can be children of another planner, like you noticed.
> 
> Tbh I thought of worker too but it seemed to capitalistic, I thought it'd be more fun to imagine them as parents and children.
> 
> I have something you might like... https://github.com/shaman-ai/llambdao. Check out **init**.py. The repo doesn't work yet but that's how I'm imagining future multi agent systems to be architected.

I think the node concept is FAR cleaner and produces less counter intuitive artifacts.

Super stoked to build DAOs that execute functions through AI agents!
