### ISSUE TITLE
Pipenv: ERROR: Package 'agent-actors' requires a different Python: 3.9.12 not in '<4.0.0,>=3.10.9'

### ISSUE THREAD

**Issue by luca-git** [shaman-ai/agent-actors#6]
On Windows 11 I've setup a specific conda environment with python 3.10.9 cuz every pipenv installation would fail with that error. Tried with multiple python versions, but I still get that error even though my python version is now exactly Python 3.10.9. On the other hand can't use poetry as the installation fails due to the impossibility of installing ray. Any help would be much appreciated. Python 3.11.3, for instance, would throw the same error, so would python 3.9.16.

**Comment by CyrusOfEden** [comment]
Ray works on Python 3.10, found issues getting it to run on Python 3.11. What error are you getting on 3.1?

**Comment by luca-git** [comment]
Had it working only on python 3.10.9 in a fresh, dedicated conda env. But I have issues with ray every time I run it, i'll close this and open another one.
